version: '3'

services:
  unsangu_com:
    container_name: unsangu_com
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: unsangu-nextjs-front:1.0
    restart: always
    ports:
      - 3939:3000
    networks:
      - obj_network

networks:
  obj_network:
    external: true